### ISSUE TITLE
slow login

### ISSUE THREAD

**Issue by MuyiwaJohnson** [rmourey26/onyx#10]
I noticed a slow login, its a cold start , i have seen this before with supabase auth and next js

**Comment by rmourey26** [comment]
thanks for the heads up!

was the delay 1 or 2 seconds or something more significant?

did the issue persist at all?  are you still experiencing latency?

**Comment by rmourey26** [comment]
Closing as issue was not pervasive

**Comment by rmourey26** [comment]
Closed
